DRAFT: calculate movements in probabilities array
PFE-Embraer/drone-swarm-search pull request #25
Opened 2023-02-14 20:35 UTC by leonardodma

Recieves: list[tuple]
Returns: list[str]

2023-02-14 23:52 UTC, leonardodma commented
Ao invés de retornar uma lista de str, decidi retornar uma lista de tipos de movimentos. Utilizei essa abordagem para deixar o código mais "tipado" e descritivo, e facilitar em uma implementação futura onde podemos trocar uma str por instruções.

Aguardo feedbacks @lfcarrete @Manuel-castanares  @lfcarrete

2023-02-15 00:00 UTC, Manuel-castanares commented on core/calculate_array_movements.py
> +    DIOGONAL_UP_LEFT = "DIOGONAL UP LEFT"
Trocar "diogonal" para diagonal nas variaveis e nas strings.

2023-02-15 00:16 UTC, Manuel-castanares commented on core/calculate_array_movements.py
> +    diagonal_movements, point_after_diagonal = calculate_diagonal_movements(
Considere checar se realmente precisa fazer movimentos diagonais antes de chamar a função. (Por exemplo, se o próximo ponto está na mesma linha ou coluna).

2023-02-15 00:21 UTC, Manuel-castanares commented on core/calculate_array_movements.py
> +        movements.append(Movements.SEARCH)
Poderiamos colocar o "search" depois de adicionar o path na lista de movimentos. Assim, só fazemos o "search" depois de chegar no ponto. Além disso, como cada "search" tem um custo de tempo maior, não precisamos fazer um search no ponto inicial (0,0). Só fariamos isso no caso em que o ponto (0, 0) também é o ponto de maior probabilidade.

2023-02-22 20:56 UTC, leonardodma commented
@Manuel-castanares  revisado!

2023-02-23 13:57 UTC, Manuel-castanares commented on core/calculate_array_movements.py
> +    if current_point[0] != next_point[0] and current_point[1] != next_point[1]:
Mudar "and" para "or"

2023-02-23 14:06 UTC, Manuel-castanares approved these changes
Boa!

2023-02-23 14:06 UTC, merged

2023-02-23 14:17 UTC, enricofd requested changes
Bom dia!

O nome dos arquivos, assim como seus paths devem ser modificados para seguir a estrutura do projeto. Sugiro fazer um merge local para ver o formato mencionado, e fazer as respectivas mudanças. Além disso alguns pontos foram elencados ao longo do código, que devem ser modificados. Mas sendo sincero, foi um ótimo trabalho, o principal ponto mesmo é formatação. Qualquer dúvida basta em chamar.

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +from typing import List, Tuple
Na versão mais atual do Python não há mais necessidade de importar listas e duplas do typing

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +from enum import Enum
Boaaaaaa

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +    UP = "UP"
Tipar (str)

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +diagonal_translator = {
tipo

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +parallel_translator = {
tipo

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +    """Calculate and return the DIAGONAL movements and current position."""
Boaaaaaaa

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +    distance_line = next_point[0] - current_point[0]
Tipar toda vez que criar uma nova var

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +    path: List[Movements] = []
pular linhas

2023-02-23 14:17 UTC, enricofd commented on core/calculate_array_movements.py
> +    """Calculate movements from a sequence of coordinates."""
pular linhas

2023-02-23 14:17 UTC, enricofd commented on tests/test_calculate_array_movements.py
> +    movements, position = calculate_diagonal_movements(current_point, next_point)
pular linha